/* File generated by summboundverify */

#define NULL ((void*)0)
#define INT_SIZE (sizeof(int) * 8)
#define LONG_SIZE (sizeof(long) * 8)
#define CHAR_SIZE (sizeof(char) * 8)
#define PTR_SIZE (sizeof(void*) * 8)
typedef void* symbolic;
typedef int state_t;
typedef unsigned int size_t;
typedef unsigned int cnstr_t;
typedef unsigned int result_t;
typedef unsigned int list_t;

cnstr_t _ULE_(symbolic var1, symbolic var2) {return 0;}
cnstr_t get_cnstr(symbolic var, size_t size) {return 0;}
int is_sat(cnstr_t cnstr) {return 0;}
result_t check_implications(char* constraint1, char* constraint2) {return 0;}
state_t save_current_state() {return 0;}
symbolic sym_var_array(char* name, size_t index, size_t size) {return 0;}
symbolic sym_var_named(char* name, size_t size) {return 0;}
void assume(cnstr_t cnstr) {return;}
void halt_all(state_t state) {return;}
void mem_addr(char* name, void* addr, size_t length) {return;}
void print_counterexamples(result_t result) {return;}
void store_cnstr(char* name, cnstr_t constraint) {return;}

cnstr_t _EQ_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _ITE_VAR_(cnstr_t cnstr1, symbolic var1, symbolic var2) {return 0;}
cnstr_t _NOT_(cnstr_t cnstr) {return 0;}
int is_certain(cnstr_t cnstr){return 0;}
void pop_pc(){return;}
void push_pc(){return;}

#define POINTER_SIZE 5
#define FUEL 5
#define ARRAY_SIZE_1 5
#define MAX_NUM_1 5

void *concrete_memrchr(const void *s, int c, size_t n)
{
  register const unsigned char *r;
  r = ((unsigned char *) s) + ((size_t) n);
  while (n)
  {
    if ((*(--r)) == ((unsigned char) c))
    {
      return (void *) r;
    }
    --n;
  }

  return 0;
}

static symbolic memrchr_rec(const unsigned char *s, unsigned char c, size_t n, symbolic current_ptr)
{
  cnstr_t end = _EQ_(n, 0);
  if (is_certain(end))
  {
    return (symbolic) 0;
  }
  push_pc();
  assume(_NOT_(end));
  symbolic val = (symbolic) ((unsigned long) (*((const unsigned char *) current_ptr)));
  cnstr_t found = _EQ_(val, (symbolic) c);
  symbolic r;
  if (is_certain(found))
  {
    r = current_ptr;
  }
  else
    if (is_certain(_NOT_(found)))
  {
    r = memrchr_rec(s, c, n - 1, (symbolic) (((unsigned long) current_ptr) - 1));
  }
  else
  {
    push_pc();
    assume(found);
    symbolic a = current_ptr;
    pop_pc();
    push_pc();
    assume(_NOT_(found));
    symbolic b = memrchr_rec(s, c, n - 1, (symbolic) (((unsigned long) current_ptr) - 1));
    pop_pc();
    r = _ITE_VAR_(found, a, b);
  }
  pop_pc();
  return _ITE_VAR_(end, (symbolic) 0, r);
}

void *memrchr(const void *s, int c, size_t n)
{
  const unsigned char *start = (const unsigned char *) s;
  symbolic end_ptr = (symbolic) ((((unsigned long) start) + ((unsigned long) n)) - 1);
  cnstr_t n_zero = _EQ_(n, 0);
  if (is_certain(n_zero))
  {
    return 0;
  }
  symbolic res = memrchr_rec(start, (unsigned char) c, n, end_ptr);
  cnstr_t res_null = _EQ_(res, (symbolic) 0);
  if (is_certain(res_null))
  {
    return 0;
  }
  else
    if (is_certain(_NOT_(res_null)))
  {
    return (void *) res;
  }
  else
  {
    push_pc();
    assume(res_null);
    symbolic a = (symbolic) 0;
    pop_pc();
    push_pc();
    assume(_NOT_(res_null));
    symbolic b = res;
    pop_pc();
    return (void *) _ITE_VAR_(res_null, a, b);
  }
}

void test_1()
{
  char s[ARRAY_SIZE_1];
  for (int s_idx_1 = 0; s_idx_1 < ARRAY_SIZE_1; s_idx_1++)
  {
    s[s_idx_1] = sym_var_array("s", s_idx_1, sizeof(char) * 8);
  }

  s[ARRAY_SIZE_1 - 1] = '\0';
  int c = sym_var_named("c", sizeof(int) * 8);
  int max_1 = MAX_NUM_1;
  assume(_ULE_(c, max_1));
  size_t n = sym_var_named("n", sizeof(size_t) * 8);
  size_t max_2 = MAX_NUM_1;
  assume(_ULE_(n, max_2));
  state_t initial_state = save_current_state();
  mem_addr("s", s, ARRAY_SIZE_1);
  void * ret1 = concrete_memrchr(s, c, n);
  cnstr_t cnstr1 = get_cnstr(&ret1, sizeof(void *) * 8);
  store_cnstr("cnctr_test1", cnstr1);
  halt_all(initial_state);
  void * ret2 = memrchr(s, c, n);
  cnstr_t cnstr2 = get_cnstr(&ret2, sizeof(void *) * 8);
  store_cnstr("summ_test1", cnstr2);
  halt_all(NULL);
  result_t result = check_implications("cnctr_test1", "summ_test1");
  print_counterexamples(result);
  return ;
}

int main()
{
  test_1();
}