/* File generated by summboundverify */

#define NULL ((void*)0)
#define INT_SIZE (sizeof(int) * 8)
#define LONG_SIZE (sizeof(long) * 8)
#define CHAR_SIZE (sizeof(char) * 8)
#define PTR_SIZE (sizeof(void*) * 8)
typedef void* symbolic;
typedef int state_t;
typedef unsigned int size_t;
typedef unsigned int cnstr_t;
typedef unsigned int result_t;
typedef unsigned int list_t;

cnstr_t _ULE_(symbolic var1, symbolic var2) {return 0;}
cnstr_t get_cnstr(symbolic var, size_t size) {return 0;}
int is_sat(cnstr_t cnstr) {return 0;}
result_t check_implications(char* constraint1, char* constraint2) {return 0;}
state_t save_current_state() {return 0;}
symbolic sym_var_array(char* name, size_t index, size_t size) {return 0;}
symbolic sym_var_named(char* name, size_t size) {return 0;}
void assume(cnstr_t cnstr) {return;}
void halt_all(state_t state) {return;}
void mem_addr(char* name, void* addr, size_t length) {return;}
void print_counterexamples(result_t result) {return;}
void store_cnstr(char* name, cnstr_t constraint) {return;}

cnstr_t _EQ_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _ITE_VAR_(cnstr_t cnstr1, symbolic var1, symbolic var2) {return 0;}
cnstr_t _NOT_(cnstr_t cnstr) {return 0;}
void allocd(void* ptr, size_t size) {return;}
void cond_write(void* ptr, symbolic c, cnstr_t pc) {return;}
int is_certain(cnstr_t cnstr){return 0;}
void pop_pc(){return;}
void push_pc(){return;}

#define POINTER_SIZE 5
#define FUEL 5
#define ARRAY_SIZE_1 5
#define MAX_NUM_1 5

void *concrete_memset(void *s, int c, size_t n)
{
  register unsigned char *p = (unsigned char *) s;
  while (n)
  {
    *(p++) = (unsigned char) c;
    --n;
  }

  return s;
}

static void *memset_recursive(void *s, int c, size_t n)
{
  cnstr_t n_zero = _EQ_(n, 0);
  if (is_certain(n_zero))
  {
    return s;
  }
  if (is_certain(_NOT_(n_zero)))
  {
    allocd(s, 1);
    cond_write(s, (symbolic) ((unsigned char) c), 1);
    return memset_recursive(((char *) s) + 1, c, n - 1);
  }
  push_pc();
  assume(n_zero);
  void *res_zero = s;
  pop_pc();
  push_pc();
  assume(_NOT_(n_zero));
  allocd(s, 1);
  cond_write(s, (symbolic) ((unsigned char) c), 1);
  void *res_step = memset_recursive(((char *) s) + 1, c, n - 1);
  pop_pc();
  return _ITE_VAR_(n_zero, (symbolic) res_zero, (symbolic) res_zero);
}

void *memset(void *s, int c, size_t n)
{
  return memset_recursive(s, c, n);
}

void test_1()
{
  char s[ARRAY_SIZE_1];
  for (int s_idx_1 = 0; s_idx_1 < ARRAY_SIZE_1; s_idx_1++)
  {
    s[s_idx_1] = sym_var_array("s", s_idx_1, sizeof(char) * 8);
  }

  s[ARRAY_SIZE_1 - 1] = '\0';
  int c = sym_var_named("c", sizeof(int) * 8);
  int max_1 = MAX_NUM_1;
  assume(_ULE_(c, max_1));
  size_t n = sym_var_named("n", sizeof(size_t) * 8);
  size_t max_2 = MAX_NUM_1;
  assume(_ULE_(n, max_2));
  state_t initial_state = save_current_state();
  void * ret1 = concrete_memset(s, c, n);
  cnstr_t cnstr1 = get_cnstr(&ret1, sizeof(void *) * 8);
  store_cnstr("cnctr_test1", cnstr1);
  halt_all(initial_state);
  void * ret2 = memset(s, c, n);
  cnstr_t cnstr2 = get_cnstr(&ret2, sizeof(void *) * 8);
  store_cnstr("summ_test1", cnstr2);
  halt_all(NULL);
  result_t result = check_implications("cnctr_test1", "summ_test1");
  print_counterexamples(result);
  return ;
}

int main()
{
  test_1();
}