/* File generated by summboundverify */

#define NULL ((void*)0)
#define INT_SIZE (sizeof(int) * 8)
#define LONG_SIZE (sizeof(long) * 8)
#define CHAR_SIZE (sizeof(char) * 8)
#define PTR_SIZE (sizeof(void*) * 8)
typedef void* symbolic;
typedef int state_t;
typedef unsigned int size_t;
typedef unsigned int cnstr_t;
typedef unsigned int result_t;
typedef unsigned int list_t;

cnstr_t _ULE_(symbolic var1, symbolic var2) {return 0;}
cnstr_t get_cnstr(symbolic var, size_t size) {return 0;}
int is_sat(cnstr_t cnstr) {return 0;}
result_t check_implications(char* constraint1, char* constraint2) {return 0;}
state_t save_current_state() {return 0;}
symbolic sym_var_array(char* name, size_t index, size_t size) {return 0;}
symbolic sym_var_named(char* name, size_t size) {return 0;}
void assume(cnstr_t cnstr) {return;}
void halt_all(state_t state) {return;}
void mem_addr(char* name, void* addr, size_t length) {return;}
void print_counterexamples(result_t result) {return;}
void store_cnstr(char* name, cnstr_t constraint) {return;}

cnstr_t _EQ_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _ITE_VAR_(cnstr_t cnstr1, symbolic var1, symbolic var2) {return 0;}
cnstr_t _NOT_(cnstr_t cnstr) {return 0;}
int is_certain(cnstr_t cnstr){return 0;}
void pop_pc(){return;}
void push_pc(){return;}

#define POINTER_SIZE 5
#define FUEL 5
#define ARRAY_SIZE_1 5

size_t concrete_strlen(const char *s)
{
  const char *a = s;
  for (; *s; s++)
    ;

  return s - a;
}

static size_t strlen_recursive(const char *s, size_t offset)
{
  symbolic current_char = *((const char *) s);
  cnstr_t is_null = _EQ_(current_char, 0);
  if (is_certain(is_null))
  {
    return offset;
  }
  else
    if (is_certain(_NOT_(is_null)))
  {
    return strlen_recursive(s + 1, offset + 1);
  }
  else
  {
    push_pc();
    assume(is_null);
    size_t len_null = offset;
    pop_pc();
    push_pc();
    assume(_NOT_(is_null));
    size_t len_not_null = strlen_recursive(s + 1, offset + 1);
    pop_pc();
    return (size_t) _ITE_VAR_(is_null, (symbolic) len_null, (symbolic) len_not_null);
  }
}

size_t strlen(const char *s)
{
  return strlen_recursive(s, 0);
}

void test_1()
{
  char s[ARRAY_SIZE_1];
  for (int s_idx_1 = 0; s_idx_1 < ARRAY_SIZE_1; s_idx_1++)
  {
    s[s_idx_1] = sym_var_array("s", s_idx_1, sizeof(char) * 8);
  }

  s[ARRAY_SIZE_1 - 1] = '\0';
  state_t initial_state = save_current_state();
  size_t ret1 = concrete_strlen(s);
  cnstr_t cnstr1 = get_cnstr(&ret1, sizeof(size_t) * 8);
  store_cnstr("cnctr_test1", cnstr1);
  halt_all(initial_state);
  size_t ret2 = strlen(s);
  cnstr_t cnstr2 = get_cnstr(&ret2, sizeof(size_t) * 8);
  store_cnstr("summ_test1", cnstr2);
  halt_all(NULL);
  result_t result = check_implications("cnctr_test1", "summ_test1");
  print_counterexamples(result);
  return ;
}

int main()
{
  test_1();
}