/* File generated by summboundverify */

#define NULL ((void*)0)
#define INT_SIZE (sizeof(int) * 8)
#define LONG_SIZE (sizeof(long) * 8)
#define CHAR_SIZE (sizeof(char) * 8)
#define PTR_SIZE (sizeof(void*) * 8)
typedef void* symbolic;
typedef int state_t;
typedef unsigned int size_t;
typedef unsigned int cnstr_t;
typedef unsigned int result_t;
typedef unsigned int list_t;

cnstr_t _ULE_(symbolic var1, symbolic var2) {return 0;}
cnstr_t get_cnstr(symbolic var, size_t size) {return 0;}
int is_sat(cnstr_t cnstr) {return 0;}
result_t check_implications(char* constraint1, char* constraint2) {return 0;}
state_t save_current_state() {return 0;}
symbolic sym_var_array(char* name, size_t index, size_t size) {return 0;}
symbolic sym_var_named(char* name, size_t size) {return 0;}
void assume(cnstr_t cnstr) {return;}
void halt_all(state_t state) {return;}
void mem_addr(char* name, void* addr, size_t length) {return;}
void print_counterexamples(result_t result) {return;}
void store_cnstr(char* name, cnstr_t constraint) {return;}

cnstr_t _AND_(cnstr_t cnstr1, cnstr_t cnstr2) {return 0;}
cnstr_t _EQ_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _GE_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _ITE_VAR_(cnstr_t cnstr1, symbolic var1, symbolic var2) {return 0;}
cnstr_t _LE_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _NOT_(cnstr_t cnstr) {return 0;}
void allocd(void* ptr, size_t size) {return;}
int is_certain(cnstr_t cnstr){return 0;}
void pop_pc(){return;}
void push_pc(){return;}

#define POINTER_SIZE 5
#define FUEL 5
#define ARRAY_SIZE_1 5

static int concrete_tolower(int c)
{
  if ((c >= 65) && (c <= 90))
  {
    return c + 32;
  }
  return c;
}

int concrete_strcasecmp(const char *_l, const char *_r)
{
  const unsigned char *l = (const unsigned char *) _l;
  const unsigned char *r = (const unsigned char *) _r;
  while ((((*l) != 0) && ((*r) != 0)) && (((*l) == (*r)) || (concrete_tolower(*l) == concrete_tolower(*r))))
  {
    l++;
    r++;
  }

  return concrete_tolower(*l) - concrete_tolower(*r);
}

static symbolic sym_tolower(symbolic c)
{
  cnstr_t is_upper = _AND_(_GE_(c, 'A'), _LE_(c, 'Z'));
  return _ITE_VAR_(is_upper, c + ('a' - 'A'), c);
}

static int strcasecmp_recursive(const char *_l, const char *_r, size_t i)
{
  allocd((void *) _l, i + 1);
  allocd((void *) _r, i + 1);
  symbolic l_val = (symbolic) ((unsigned char) _l[i]);
  symbolic r_val = (symbolic) ((unsigned char) _r[i]);
  symbolic tl = sym_tolower(l_val);
  symbolic tr = sym_tolower(r_val);
  cnstr_t l_null = _EQ_(l_val, 0);
  cnstr_t r_null = _EQ_(r_val, 0);
  cnstr_t eq_case = _EQ_(tl, tr);
  cnstr_t loop_cond = _AND_(_NOT_(l_null), _AND_(_NOT_(r_null), eq_case));
  if (is_certain(loop_cond))
  {
    return strcasecmp_recursive(_l, _r, i + 1);
  }
  else
    if (is_certain(_NOT_(loop_cond)))
  {
    return (int) (tl - tr);
  }
  else
  {
    push_pc();
    assume(loop_cond);
    int res_continue = strcasecmp_recursive(_l, _r, i + 1);
    pop_pc();
    push_pc();
    assume(_NOT_(loop_cond));
    int res_break = (int) (tl - tr);
    pop_pc();
    return (int) _ITE_VAR_(loop_cond, (symbolic) res_continue, (symbolic) res_break);
  }
}

int strcasecmp(const char *_l, const char *_r)
{
  return strcasecmp_recursive(_l, _r, 0);
}

void test_1()
{
  char _l[ARRAY_SIZE_1];
  for (int _l_idx_1 = 0; _l_idx_1 < ARRAY_SIZE_1; _l_idx_1++)
  {
    _l[_l_idx_1] = sym_var_array("_l", _l_idx_1, sizeof(char) * 8);
  }

  _l[ARRAY_SIZE_1 - 1] = '\0';
  char _r[ARRAY_SIZE_1];
  for (int _r_idx_1 = 0; _r_idx_1 < ARRAY_SIZE_1; _r_idx_1++)
  {
    _r[_r_idx_1] = sym_var_array("_r", _r_idx_1, sizeof(char) * 8);
  }

  _r[ARRAY_SIZE_1 - 1] = '\0';
  state_t initial_state = save_current_state();
  int ret1 = concrete_strcasecmp(_l, _r);
  cnstr_t cnstr1 = get_cnstr(&ret1, sizeof(int) * 8);
  store_cnstr("cnctr_test1", cnstr1);
  halt_all(initial_state);
  int ret2 = strcasecmp(_l, _r);
  cnstr_t cnstr2 = get_cnstr(&ret2, sizeof(int) * 8);
  store_cnstr("summ_test1", cnstr2);
  halt_all(NULL);
  result_t result = check_implications("cnctr_test1", "summ_test1");
  print_counterexamples(result);
  return ;
}

int main()
{
  test_1();
}