/* File generated by summboundverify */

#define NULL ((void*)0)
#define INT_SIZE (sizeof(int) * 8)
#define LONG_SIZE (sizeof(long) * 8)
#define CHAR_SIZE (sizeof(char) * 8)
#define PTR_SIZE (sizeof(void*) * 8)
typedef void* symbolic;
typedef int state_t;
typedef unsigned int size_t;
typedef unsigned int cnstr_t;
typedef unsigned int result_t;
typedef unsigned int list_t;

cnstr_t _ULE_(symbolic var1, symbolic var2) {return 0;}
cnstr_t get_cnstr(symbolic var, size_t size) {return 0;}
int is_sat(cnstr_t cnstr) {return 0;}
result_t check_implications(char* constraint1, char* constraint2) {return 0;}
state_t save_current_state() {return 0;}
symbolic sym_var_array(char* name, size_t index, size_t size) {return 0;}
symbolic sym_var_named(char* name, size_t size) {return 0;}
void assume(cnstr_t cnstr) {return;}
void halt_all(state_t state) {return;}
void mem_addr(char* name, void* addr, size_t length) {return;}
void print_counterexamples(result_t result) {return;}
void store_cnstr(char* name, cnstr_t constraint) {return;}

cnstr_t _EQ_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _ITE_VAR_(cnstr_t cnstr1, symbolic var1, symbolic var2) {return 0;}
cnstr_t _NOT_(cnstr_t cnstr) {return 0;}
int is_certain(cnstr_t cnstr){return 0;}
void pop_pc(){return;}
void push_pc(){return;}

#define POINTER_SIZE 5
#define FUEL 5
#define ARRAY_SIZE_1 5
#define MAX_NUM_1 5

char *concrete_strrchr(register const char *s, int c)
{
  register const char *p;
  p = 0;
  do
  {
    if ((*s) == ((char) c))
    {
      p = s;
    }
  }
  while (*(s++));
  return (char *) p;
}

static symbolic strrchr_rec(const char *s, char c, symbolic last_found)
{
  cnstr_t is_null = _EQ_(*s, '\0');
  cnstr_t is_match = _EQ_(*s, c);
  if (is_certain(is_null))
  {
    return _ITE_VAR_(is_match, (symbolic) s, last_found);
  }
  if (is_certain(_NOT_(is_null)))
  {
    symbolic current_found;
    if (is_certain(is_match))
    {
      current_found = (symbolic) s;
    }
    else
      if (is_certain(_NOT_(is_match)))
    {
      current_found = last_found;
    }
    else
    {
      push_pc();
      assume(is_match);
      symbolic a = (symbolic) s;
      pop_pc();
      push_pc();
      assume(_NOT_(is_match));
      symbolic b = last_found;
      pop_pc();
      current_found = _ITE_VAR_(is_match, a, b);
    }
    return strrchr_rec(s + 1, c, current_found);
  }
  push_pc();
  assume(is_null);
  symbolic r_null = _ITE_VAR_(is_match, (symbolic) s, last_found);
  pop_pc();
  push_pc();
  assume(_NOT_(is_null));
  symbolic current_found;
  if (is_certain(is_match))
  {
    current_found = (symbolic) s;
  }
  else
    if (is_certain(_NOT_(is_match)))
  {
    current_found = last_found;
  }
  else
  {
    push_pc();
    assume(is_match);
    symbolic a = (symbolic) s;
    pop_pc();
    push_pc();
    assume(_NOT_(is_match));
    symbolic b = last_found;
    pop_pc();
    current_found = _ITE_VAR_(is_match, a, b);
  }
  symbolic r_not_null = strrchr_rec(s + 1, c, current_found);
  pop_pc();
  return _ITE_VAR_(is_null, r_null, r_not_null);
}

char *strrchr(const char *s, int c)
{
  return (char *) strrchr_rec(s, (char) c, (symbolic) 0);
}

void test_1()
{
  char s[ARRAY_SIZE_1];
  for (int s_idx_1 = 0; s_idx_1 < ARRAY_SIZE_1; s_idx_1++)
  {
    s[s_idx_1] = sym_var_array("s", s_idx_1, sizeof(char) * 8);
  }

  s[ARRAY_SIZE_1 - 1] = '\0';
  int c = sym_var_named("c", sizeof(int) * 8);
  int max_1 = MAX_NUM_1;
  assume(_ULE_(c, max_1));
  state_t initial_state = save_current_state();
  char * ret1 = concrete_strrchr(s, c);
  cnstr_t cnstr1 = get_cnstr(&ret1, sizeof(char *) * 8);
  store_cnstr("cnctr_test1", cnstr1);
  halt_all(initial_state);
  char * ret2 = strrchr(s, c);
  cnstr_t cnstr2 = get_cnstr(&ret2, sizeof(char *) * 8);
  store_cnstr("summ_test1", cnstr2);
  halt_all(NULL);
  result_t result = check_implications("cnctr_test1", "summ_test1");
  print_counterexamples(result);
  return ;
}

int main()
{
  test_1();
}