/* File generated by summboundverify */

#define NULL ((void*)0)
#define INT_SIZE (sizeof(int) * 8)
#define LONG_SIZE (sizeof(long) * 8)
#define CHAR_SIZE (sizeof(char) * 8)
#define PTR_SIZE (sizeof(void*) * 8)
typedef void* symbolic;
typedef int state_t;
typedef unsigned int size_t;
typedef unsigned int cnstr_t;
typedef unsigned int result_t;
typedef unsigned int list_t;

cnstr_t _ULE_(symbolic var1, symbolic var2) {return 0;}
cnstr_t get_cnstr(symbolic var, size_t size) {return 0;}
int is_sat(cnstr_t cnstr) {return 0;}
result_t check_implications(char* constraint1, char* constraint2) {return 0;}
state_t save_current_state() {return 0;}
symbolic sym_var_array(char* name, size_t index, size_t size) {return 0;}
symbolic sym_var_named(char* name, size_t size) {return 0;}
void assume(cnstr_t cnstr) {return;}
void halt_all(state_t state) {return;}
void mem_addr(char* name, void* addr, size_t length) {return;}
void print_counterexamples(result_t result) {return;}
void store_cnstr(char* name, cnstr_t constraint) {return;}

cnstr_t _EQ_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _ITE_VAR_(cnstr_t cnstr1, symbolic var1, symbolic var2) {return 0;}
cnstr_t _NOT_(cnstr_t cnstr) {return 0;}
int is_certain(cnstr_t cnstr){return 0;}
void pop_pc(){return;}
void push_pc(){return;}

#define POINTER_SIZE 5
#define FUEL 5
#define ARRAY_SIZE_1 5
#define MAX_NUM_1 5

int concrete_strncmp(register const char *s1, register const char *s2, size_t n)
{
  int r = 0;
  while (((n--) && ((r = ((int) (*((unsigned char *) s1))) - (*((unsigned char *) (s2++)))) == 0)) && (*(s1++)))
    ;

  return r;
}

static symbolic strncmp_recursive(const char *s1, const char *s2, size_t n)
{
  cnstr_t n_zero = _EQ_(n, 0);
  if (is_certain(n_zero))
  {
    return 0;
  }
  else
    if (is_certain(_NOT_(n_zero)))
  {
    symbolic c1 = (symbolic) ((unsigned char) (*s1));
    symbolic c2 = (symbolic) ((unsigned char) (*s2));
    cnstr_t eq = _EQ_(c1, c2);
    cnstr_t s1_null = _EQ_(c1, 0);
    if (is_certain(eq))
    {
      if (is_certain(s1_null))
      {
        return 0;
      }
      else
        if (is_certain(_NOT_(s1_null)))
      {
        return strncmp_recursive(s1 + 1, s2 + 1, n - 1);
      }
      else
      {
        push_pc();
        assume(s1_null);
        symbolic r1 = 0;
        pop_pc();
        push_pc();
        assume(_NOT_(s1_null));
        symbolic r2 = strncmp_recursive(s1 + 1, s2 + 1, n - 1);
        pop_pc();
        return _ITE_VAR_(s1_null, r1, r2);
      }
    }
    else
      if (is_certain(_NOT_(eq)))
    {
      return c1 - c2;
    }
    else
    {
      push_pc();
      assume(eq);
      symbolic res_eq;
      if (is_certain(s1_null))
      {
        res_eq = 0;
      }
      else
        if (is_certain(_NOT_(s1_null)))
      {
        res_eq = strncmp_recursive(s1 + 1, s2 + 1, n - 1);
      }
      else
      {
        push_pc();
        assume(s1_null);
        symbolic re1 = 0;
        pop_pc();
        push_pc();
        assume(_NOT_(s1_null));
        symbolic re2 = strncmp_recursive(s1 + 1, s2 + 1, n - 1);
        pop_pc();
        res_eq = _ITE_VAR_(s1_null, re1, re2);
      }
      pop_pc();
      push_pc();
      assume(_NOT_(eq));
      symbolic res_neq = c1 - c2;
      pop_pc();
      return _ITE_VAR_(eq, res_eq, res_neq);
    }
  }
  else
  {
    push_pc();
    assume(n_zero);
    symbolic r_zero = 0;
    pop_pc();
    push_pc();
    assume(_NOT_(n_zero));
    symbolic c1 = (symbolic) ((unsigned char) (*s1));
    symbolic c2 = (symbolic) ((unsigned char) (*s2));
    cnstr_t eq = _EQ_(c1, c2);
    cnstr_t s1_null = _EQ_(c1, 0);
    symbolic r_nonzero;
    if (is_certain(eq))
    {
      if (is_certain(s1_null))
        r_nonzero = 0;
      else
        if (is_certain(_NOT_(s1_null)))
        r_nonzero = strncmp_recursive(s1 + 1, s2 + 1, n - 1);
      else
      {
        push_pc();
        assume(s1_null);
        symbolic r1 = 0;
        pop_pc();
        push_pc();
        assume(_NOT_(s1_null));
        symbolic r2 = strncmp_recursive(s1 + 1, s2 + 1, n - 1);
        pop_pc();
        r_nonzero = _ITE_VAR_(s1_null, r1, r2);
      }
    }
    else
      if (is_certain(_NOT_(eq)))
    {
      r_nonzero = c1 - c2;
    }
    else
    {
      push_pc();
      assume(eq);
      symbolic res_eq;
      if (is_certain(s1_null))
        res_eq = 0;
      else
        if (is_certain(_NOT_(s1_null)))
        res_eq = strncmp_recursive(s1 + 1, s2 + 1, n - 1);
      else
      {
        push_pc();
        assume(s1_null);
        symbolic re1 = 0;
        pop_pc();
        push_pc();
        assume(_NOT_(s1_null));
        symbolic re2 = strncmp_recursive(s1 + 1, s2 + 1, n - 1);
        pop_pc();
        res_eq = _ITE_VAR_(s1_null, re1, re2);
      }
      pop_pc();
      push_pc();
      assume(_NOT_(eq));
      symbolic res_neq = c1 - c2;
      pop_pc();
      r_nonzero = _ITE_VAR_(eq, res_eq, res_neq);
    }
    pop_pc();
    return _ITE_VAR_(n_zero, r_zero, r_nonzero);
  }
}

int strncmp(const char *s1, const char *s2, size_t n)
{
  return (int) strncmp_recursive(s1, s2, n);
}

void test_1()
{
  char s1[ARRAY_SIZE_1];
  for (int s1_idx_1 = 0; s1_idx_1 < ARRAY_SIZE_1; s1_idx_1++)
  {
    s1[s1_idx_1] = sym_var_array("s1", s1_idx_1, sizeof(char) * 8);
  }

  s1[ARRAY_SIZE_1 - 1] = '\0';
  char s2[ARRAY_SIZE_1];
  for (int s2_idx_1 = 0; s2_idx_1 < ARRAY_SIZE_1; s2_idx_1++)
  {
    s2[s2_idx_1] = sym_var_array("s2", s2_idx_1, sizeof(char) * 8);
  }

  s2[ARRAY_SIZE_1 - 1] = '\0';
  size_t n = sym_var_named("n", sizeof(size_t) * 8);
  size_t max_1 = MAX_NUM_1;
  assume(_ULE_(n, max_1));
  state_t initial_state = save_current_state();
  int ret1 = concrete_strncmp(s1, s2, n);
  cnstr_t cnstr1 = get_cnstr(&ret1, sizeof(int) * 8);
  store_cnstr("cnctr_test1", cnstr1);
  halt_all(initial_state);
  int ret2 = strncmp(s1, s2, n);
  cnstr_t cnstr2 = get_cnstr(&ret2, sizeof(int) * 8);
  store_cnstr("summ_test1", cnstr2);
  halt_all(NULL);
  result_t result = check_implications("cnctr_test1", "summ_test1");
  print_counterexamples(result);
  return ;
}

int main()
{
  test_1();
}