/* File generated by summboundverify */

#define NULL ((void*)0)
#define INT_SIZE (sizeof(int) * 8)
#define LONG_SIZE (sizeof(long) * 8)
#define CHAR_SIZE (sizeof(char) * 8)
#define PTR_SIZE (sizeof(void*) * 8)
typedef void* symbolic;
typedef int state_t;
typedef unsigned int size_t;
typedef unsigned int cnstr_t;
typedef unsigned int result_t;
typedef unsigned int list_t;

cnstr_t _ULE_(symbolic var1, symbolic var2) {return 0;}
cnstr_t get_cnstr(symbolic var, size_t size) {return 0;}
int is_sat(cnstr_t cnstr) {return 0;}
result_t check_implications(char* constraint1, char* constraint2) {return 0;}
state_t save_current_state() {return 0;}
symbolic sym_var_array(char* name, size_t index, size_t size) {return 0;}
symbolic sym_var_named(char* name, size_t size) {return 0;}
void assume(cnstr_t cnstr) {return;}
void halt_all(state_t state) {return;}
void mem_addr(char* name, void* addr, size_t length) {return;}
void print_counterexamples(result_t result) {return;}
void store_cnstr(char* name, cnstr_t constraint) {return;}

cnstr_t _EQ_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _ITE_VAR_(cnstr_t cnstr1, symbolic var1, symbolic var2) {return 0;}
cnstr_t _NOT_(cnstr_t cnstr) {return 0;}
void allocd(void* ptr, size_t size) {return;}
int is_certain(cnstr_t cnstr){return 0;}
void pop_pc(){return;}
void push_pc(){return;}

#define POINTER_SIZE 5
#define FUEL 5
#define ARRAY_SIZE_1 5
#define MAX_NUM_1 5

size_t concrete_strnlen(const char *s, size_t max)
{
  register const char *p = s;
  while (max && (*p))
  {
    ++p;
    --max;
  }

  return p - s;
}

static symbolic strnlen_rec(const char *s, size_t max)
{
  cnstr_t max_zero = _EQ_(max, 0);
  if (is_certain(max_zero))
  {
    return 0;
  }
  allocd(s, 1);
  cnstr_t s_null = _EQ_(*s, '\0');
  if (is_certain(s_null))
  {
    return 0;
  }
  if (is_certain(_NOT_(max_zero)) && is_certain(_NOT_(s_null)))
  {
    return 1 + strnlen_rec(s + 1, max - 1);
  }
  push_pc();
  assume(max_zero);
  symbolic r_zero = 0;
  pop_pc();
  push_pc();
  assume(_NOT_(max_zero));
  push_pc();
  assume(s_null);
  symbolic r_null = 0;
  pop_pc();
  push_pc();
  assume(_NOT_(s_null));
  symbolic r_rec = 1 + strnlen_rec(s + 1, max - 1);
  pop_pc();
  symbolic r_not_zero = _ITE_VAR_(s_null, r_null, r_rec);
  pop_pc();
  return _ITE_VAR_(max_zero, r_zero, r_not_zero);
}

size_t strnlen(const char *s, size_t max)
{
  return (size_t) strnlen_rec(s, max);
}

void test_1()
{
  char s[ARRAY_SIZE_1];
  for (int s_idx_1 = 0; s_idx_1 < ARRAY_SIZE_1; s_idx_1++)
  {
    s[s_idx_1] = sym_var_array("s", s_idx_1, sizeof(char) * 8);
  }

  s[ARRAY_SIZE_1 - 1] = '\0';
  size_t max = sym_var_named("max", sizeof(size_t) * 8);
  size_t max_1 = MAX_NUM_1;
  assume(_ULE_(max, max_1));
  state_t initial_state = save_current_state();
  size_t ret1 = concrete_strnlen(s, max);
  cnstr_t cnstr1 = get_cnstr(&ret1, sizeof(size_t) * 8);
  store_cnstr("cnctr_test1", cnstr1);
  halt_all(initial_state);
  size_t ret2 = strnlen(s, max);
  cnstr_t cnstr2 = get_cnstr(&ret2, sizeof(size_t) * 8);
  store_cnstr("summ_test1", cnstr2);
  halt_all(NULL);
  result_t result = check_implications("cnctr_test1", "summ_test1");
  print_counterexamples(result);
  return ;
}

int main()
{
  test_1();
}