/* File generated by summboundverify */

#define NULL ((void*)0)
#define INT_SIZE (sizeof(int) * 8)
#define LONG_SIZE (sizeof(long) * 8)
#define CHAR_SIZE (sizeof(char) * 8)
#define PTR_SIZE (sizeof(void*) * 8)
typedef void* symbolic;
typedef int state_t;
typedef unsigned int size_t;
typedef unsigned int cnstr_t;
typedef unsigned int result_t;
typedef unsigned int list_t;

cnstr_t _ULE_(symbolic var1, symbolic var2) {return 0;}
cnstr_t get_cnstr(symbolic var, size_t size) {return 0;}
int is_sat(cnstr_t cnstr) {return 0;}
result_t check_implications(char* constraint1, char* constraint2) {return 0;}
state_t save_current_state() {return 0;}
symbolic sym_var_array(char* name, size_t index, size_t size) {return 0;}
symbolic sym_var_named(char* name, size_t size) {return 0;}
void assume(cnstr_t cnstr) {return;}
void halt_all(state_t state) {return;}
void mem_addr(char* name, void* addr, size_t length) {return;}
void print_counterexamples(result_t result) {return;}
void store_cnstr(char* name, cnstr_t constraint) {return;}

cnstr_t _EQ_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _ITE_VAR_(cnstr_t cnstr1, symbolic var1, symbolic var2) {return 0;}
cnstr_t _NOT_(cnstr_t cnstr) {return 0;}
int is_certain(cnstr_t cnstr){return 0;}
void pop_pc(){return;}
void push_pc(){return;}

#define POINTER_SIZE 5
#define FUEL 5
#define ARRAY_SIZE_1 5
#define MAX_NUM_1 5

char *concrete_strchr(register const char *s, int c)
{
  do
  {
    if ((*s) == ((char) c))
    {
      return (char *) s;
    }
  }
  while (*(s++));
  return 0;
}

char *strchr(const char *s, int c)
{
  symbolic sym_c = (symbolic) ((char) c);
  cnstr_t found = _EQ_(*s, sym_c);
  cnstr_t null = _EQ_(*s, '\0');
  if (is_certain(found))
  {
    return (char *) s;
  }
  if (is_certain(_NOT_(found)))
  {
    if (is_certain(null))
    {
      return (char *) 0;
    }
    if (is_certain(_NOT_(null)))
    {
      return strchr(s + 1, c);
    }
    push_pc();
    assume(null);
    symbolic r_null = (symbolic) ((char *) 0);
    pop_pc();
    push_pc();
    assume(_NOT_(null));
    symbolic r_rec = (symbolic) strchr(s + 1, c);
    pop_pc();
    return (char *) _ITE_VAR_(null, r_null, r_rec);
  }
  push_pc();
  assume(found);
  symbolic r_found = (symbolic) ((char *) s);
  pop_pc();
  push_pc();
  assume(_NOT_(found));
  cnstr_t null_inner = _EQ_(*s, '\0');
  symbolic r_not_found;
  if (is_certain(null_inner))
  {
    r_not_found = (symbolic) ((char *) 0);
  }
  else
    if (is_certain(_NOT_(null_inner)))
  {
    r_not_found = (symbolic) strchr(s + 1, c);
  }
  else
  {
    push_pc();
    assume(null_inner);
    symbolic rn = (symbolic) ((char *) 0);
    pop_pc();
    push_pc();
    assume(_NOT_(null_inner));
    symbolic rr = (symbolic) strchr(s + 1, c);
    pop_pc();
    r_not_found = _ITE_VAR_(null_inner, rn, rr);
  }
  pop_pc();
  return (char *) _ITE_VAR_(found, r_found, r_not_found);
}

void test_1()
{
  char s[ARRAY_SIZE_1];
  for (int s_idx_1 = 0; s_idx_1 < ARRAY_SIZE_1; s_idx_1++)
  {
    s[s_idx_1] = sym_var_array("s", s_idx_1, sizeof(char) * 8);
  }

  s[ARRAY_SIZE_1 - 1] = '\0';
  int c = sym_var_named("c", sizeof(int) * 8);
  int max_1 = MAX_NUM_1;
  assume(_ULE_(c, max_1));
  state_t initial_state = save_current_state();
  char * ret1 = concrete_strchr(s, c);
  cnstr_t cnstr1 = get_cnstr(&ret1, sizeof(char *) * 8);
  store_cnstr("cnctr_test1", cnstr1);
  halt_all(initial_state);
  char * ret2 = strchr(s, c);
  cnstr_t cnstr2 = get_cnstr(&ret2, sizeof(char *) * 8);
  store_cnstr("summ_test1", cnstr2);
  halt_all(NULL);
  result_t result = check_implications("cnctr_test1", "summ_test1");
  print_counterexamples(result);
  return ;
}

int main()
{
  test_1();
}