/* File generated by summboundverify */

#define NULL ((void*)0)
#define INT_SIZE (sizeof(int) * 8)
#define LONG_SIZE (sizeof(long) * 8)
#define CHAR_SIZE (sizeof(char) * 8)
#define PTR_SIZE (sizeof(void*) * 8)
typedef void* symbolic;
typedef int state_t;
typedef unsigned int size_t;
typedef unsigned int cnstr_t;
typedef unsigned int result_t;
typedef unsigned int list_t;

cnstr_t _ULE_(symbolic var1, symbolic var2) {return 0;}
cnstr_t get_cnstr(symbolic var, size_t size) {return 0;}
int is_sat(cnstr_t cnstr) {return 0;}
result_t check_implications(char* constraint1, char* constraint2) {return 0;}
state_t save_current_state() {return 0;}
symbolic sym_var_array(char* name, size_t index, size_t size) {return 0;}
symbolic sym_var_named(char* name, size_t size) {return 0;}
void assume(cnstr_t cnstr) {return;}
void halt_all(state_t state) {return;}
void mem_addr(char* name, void* addr, size_t length) {return;}
void print_counterexamples(result_t result) {return;}
void store_cnstr(char* name, cnstr_t constraint) {return;}

cnstr_t _AND_(cnstr_t cnstr1, cnstr_t cnstr2) {return 0;}
cnstr_t _EQ_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _GT_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _ITE_VAR_(cnstr_t cnstr1, symbolic var1, symbolic var2) {return 0;}
cnstr_t _NOT_(cnstr_t cnstr) {return 0;}
void cond_write(void* ptr, symbolic c, cnstr_t pc) {return;}
int is_certain(cnstr_t cnstr){return 0;}
void pop_pc(){return;}
void push_pc(){return;}

#define POINTER_SIZE 5
#define FUEL 5
#define ARRAY_SIZE_1 5
#define MAX_NUM_1 5

size_t concrete_strlcpy(register char *dst, register const char *src, size_t n)
{
  const char *src0 = src;
  char dummy[1];
  if (!n)
  {
    dst = dummy;
  }
  else
  {
    --n;
  }
  while ((*dst = *src) != 0)
  {
    if (n)
    {
      --n;
      ++dst;
    }
    ++src;
  }

  return src - src0;
}

static symbolic strlcpy_rec(char *dst, const char *src, size_t n, cnstr_t guard)
{
  symbolic c = (symbolic) ((unsigned long) (*((const unsigned char *) src)));
  cnstr_t end = _EQ_(c, 0);
  cond_write(dst, c, guard);
  if (is_certain(end))
  {
    return (symbolic) 0;
  }
  push_pc();
  assume(_NOT_(end));
  cnstr_t g = _AND_(guard, _NOT_(end));
  symbolic res;
  if (is_certain(_EQ_(n, 0)))
  {
    res = (symbolic) 1;
    push_pc();
    assume(_NOT_(end));
    pop_pc();
  }
  pop_pc();
  return res;
}

static symbolic strlcpy_step(char *dst, const char *src, size_t n, cnstr_t guard)
{
  symbolic c = (symbolic) ((unsigned long) (*((const unsigned char *) src)));
  cnstr_t end = _EQ_(c, 0);
  cond_write(dst, c, guard);
  if (is_certain(end))
  {
    return (symbolic) 0;
  }
  push_pc();
  assume(_NOT_(end));
  cnstr_t g = _AND_(guard, _NOT_(end));
  symbolic next_len;
  cnstr_t n_pos = _GT_(n, 0);
  if (is_certain(n_pos))
  {
    next_len = (symbolic) (((unsigned long) 1) + ((unsigned long) strlcpy_step(dst + 1, src + 1, n - 1, g)));
  }
  else
    if (is_certain(_NOT_(n_pos)))
  {
    next_len = (symbolic) (((unsigned long) 1) + ((unsigned long) strlcpy_step(dst, src + 1, n, g)));
  }
  else
  {
    push_pc();
    assume(n_pos);
    symbolic a = (symbolic) (((unsigned long) 1) + ((unsigned long) strlcpy_step(dst + 1, src + 1, n - 1, _AND_(g, n_pos))));
    pop_pc();
    push_pc();
    assume(_NOT_(n_pos));
    symbolic b = (symbolic) (((unsigned long) 1) + ((unsigned long) strlcpy_step(dst, src + 1, n, _AND_(g, _NOT_(n_pos)))));
    pop_pc();
    next_len = _ITE_VAR_(n_pos, a, b);
  }
  pop_pc();
  return _ITE_VAR_(end, (symbolic) 0, next_len);
}

size_t strlcpy(char *dst, const char *src, size_t n)
{
  cnstr_t n_zero = _EQ_(n, 0);
  symbolic res;
  if (is_certain(n_zero))
  {
    res = (symbolic) strlcpy_step((char *) 0, src, 0, 1);
  }
  else
    if (is_certain(_NOT_(n_zero)))
  {
    res = (symbolic) strlcpy_step(dst, src, n - 1, 1);
  }
  else
  {
    push_pc();
    assume(n_zero);
    symbolic a = (symbolic) strlcpy_step((char *) 0, src, 0, n_zero);
    pop_pc();
    push_pc();
    assume(_NOT_(n_zero));
    symbolic b = (symbolic) strlcpy_step(dst, src, n - 1, _NOT_(n_zero));
    pop_pc();
    res = _ITE_VAR_(n_zero, a, b);
  }
  return (size_t) ((unsigned long) res);
}

void test_1()
{
  char dst[ARRAY_SIZE_1];
  for (int dst_idx_1 = 0; dst_idx_1 < ARRAY_SIZE_1; dst_idx_1++)
  {
    dst[dst_idx_1] = sym_var_array("dst", dst_idx_1, sizeof(char) * 8);
  }

  dst[ARRAY_SIZE_1 - 1] = '\0';
  char src[ARRAY_SIZE_1];
  for (int src_idx_1 = 0; src_idx_1 < ARRAY_SIZE_1; src_idx_1++)
  {
    src[src_idx_1] = sym_var_array("src", src_idx_1, sizeof(char) * 8);
  }

  src[ARRAY_SIZE_1 - 1] = '\0';
  size_t n = sym_var_named("n", sizeof(size_t) * 8);
  size_t max_1 = MAX_NUM_1;
  assume(_ULE_(n, max_1));
  state_t initial_state = save_current_state();
  mem_addr("dst", dst, ARRAY_SIZE_1);
  mem_addr("src", src, ARRAY_SIZE_1);
  size_t ret1 = concrete_strlcpy(dst, src, n);
  cnstr_t cnstr1 = get_cnstr(&ret1, sizeof(size_t) * 8);
  store_cnstr("cnctr_test1", cnstr1);
  halt_all(initial_state);
  size_t ret2 = strlcpy(dst, src, n);
  cnstr_t cnstr2 = get_cnstr(&ret2, sizeof(size_t) * 8);
  store_cnstr("summ_test1", cnstr2);
  halt_all(NULL);
  result_t result = check_implications("cnctr_test1", "summ_test1");
  print_counterexamples(result);
  return ;
}

int main()
{
  test_1();
}