/* File generated by summboundverify */

#define NULL ((void*)0)
#define INT_SIZE (sizeof(int) * 8)
#define LONG_SIZE (sizeof(long) * 8)
#define CHAR_SIZE (sizeof(char) * 8)
#define PTR_SIZE (sizeof(void*) * 8)
typedef void* symbolic;
typedef int state_t;
typedef unsigned int size_t;
typedef unsigned int cnstr_t;
typedef unsigned int result_t;
typedef unsigned int list_t;

cnstr_t _ULE_(symbolic var1, symbolic var2) {return 0;}
cnstr_t get_cnstr(symbolic var, size_t size) {return 0;}
int is_sat(cnstr_t cnstr) {return 0;}
result_t check_implications(char* constraint1, char* constraint2) {return 0;}
state_t save_current_state() {return 0;}
symbolic sym_var_array(char* name, size_t index, size_t size) {return 0;}
symbolic sym_var_named(char* name, size_t size) {return 0;}
void assume(cnstr_t cnstr) {return;}
void halt_all(state_t state) {return;}
void mem_addr(char* name, void* addr, size_t length) {return;}
void print_counterexamples(result_t result) {return;}
void store_cnstr(char* name, cnstr_t constraint) {return;}

cnstr_t _EQ_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _NOT_(cnstr_t cnstr) {return 0;}
void cond_write(void* ptr, symbolic c, cnstr_t pc) {return;}
int is_certain(cnstr_t cnstr){return 0;}
void* mem_alloc(size_t bytes) {return 0;}

#define POINTER_SIZE 5
#define FUEL 5
#define ARRAY_SIZE_1 5

static size_t concrete_strlen(const char *s)
{
  size_t len = 0;
  while (s[len] != '\0')
  {
    len++;
  }

  return len;
}

static void *concrete_memcpy(void *dest, const void *src, size_t n)
{
  unsigned char *d = (unsigned char *) dest;
  const unsigned char *s = (const unsigned char *) src;
  for (size_t i = 0; i < n; i++)
  {
    d[i] = s[i];
  }

  return dest;
}

char *concrete_strdup(const char *s)
{
  size_t l = concrete_strlen(s);
  char *d = (char *) malloc(l + 1);
  if (!d)
  {
    return 0;
  }
  return (char *) concrete_memcpy(d, s, l + 1);
}

static size_t sym_strlen(const char *s)
{
  if (is_certain(_EQ_(*s, 0)))
  {
    return 0;
  }
  return 1 + sym_strlen(s + 1);
}

char *strdup(const char *s)
{
  size_t len = sym_strlen(s);
  char *d = (char *) mem_alloc(len + 1);
  if (d == 0)
  {
    return 0;
  }
  for (size_t i = 0; i <= len; i++)
  {
    cond_write(d + i, *(s + i), _NOT_(_EQ_(0, 0)));
  }

  return d;
}

void test_1()
{
  char s[ARRAY_SIZE_1];
  for (int s_idx_1 = 0; s_idx_1 < ARRAY_SIZE_1; s_idx_1++)
  {
    s[s_idx_1] = sym_var_array("s", s_idx_1, sizeof(char) * 8);
  }

  s[ARRAY_SIZE_1 - 1] = '\0';
  state_t initial_state = save_current_state();
  char * ret1 = concrete_strdup(s);
  cnstr_t cnstr1 = get_cnstr(&ret1, sizeof(char *) * 8);
  store_cnstr("cnctr_test1", cnstr1);
  halt_all(initial_state);
  char * ret2 = strdup(s);
  cnstr_t cnstr2 = get_cnstr(&ret2, sizeof(char *) * 8);
  store_cnstr("summ_test1", cnstr2);
  halt_all(NULL);
  result_t result = check_implications("cnctr_test1", "summ_test1");
  print_counterexamples(result);
  return ;
}

int main()
{
  test_1();
}