/* File generated by summboundverify */

#define NULL ((void*)0)
#define INT_SIZE (sizeof(int) * 8)
#define LONG_SIZE (sizeof(long) * 8)
#define CHAR_SIZE (sizeof(char) * 8)
#define PTR_SIZE (sizeof(void*) * 8)
typedef void* symbolic;
typedef int state_t;
typedef unsigned int size_t;
typedef unsigned int cnstr_t;
typedef unsigned int result_t;
typedef unsigned int list_t;

cnstr_t _ULE_(symbolic var1, symbolic var2) {return 0;}
cnstr_t get_cnstr(symbolic var, size_t size) {return 0;}
int is_sat(cnstr_t cnstr) {return 0;}
result_t check_implications(char* constraint1, char* constraint2) {return 0;}
state_t save_current_state() {return 0;}
symbolic sym_var_array(char* name, size_t index, size_t size) {return 0;}
symbolic sym_var_named(char* name, size_t size) {return 0;}
void assume(cnstr_t cnstr) {return;}
void halt_all(state_t state) {return;}
void mem_addr(char* name, void* addr, size_t length) {return;}
void print_counterexamples(result_t result) {return;}
void store_cnstr(char* name, cnstr_t constraint) {return;}

cnstr_t _AND_(cnstr_t cnstr1, cnstr_t cnstr2) {return 0;}
cnstr_t _EQ_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _ITE_VAR_(cnstr_t cnstr1, symbolic var1, symbolic var2) {return 0;}
cnstr_t _NOT_(cnstr_t cnstr) {return 0;}
void cond_write(void* ptr, symbolic c, cnstr_t pc) {return;}
int is_certain(cnstr_t cnstr){return 0;}
void* mem_alloc(size_t bytes) {return 0;}
void pop_pc(){return;}
void push_pc(){return;}

#define POINTER_SIZE 5
#define FUEL 5
#define ARRAY_SIZE_1 5
#define MAX_NUM_1 5

void *concrete_memcpy(void *s1, const void *s2, size_t n)
{
  register char *r1 = s1;
  register const char *r2 = s2;
  while (n)
  {
    *(r1++) = *(r2++);
    --n;
  }

  return s1;
}

size_t concrete_strlen(const char *s)
{
  register const char *p;
  for (p = s; *p; p++)
    ;

  return p - s;
}

char *concrete_strdup(register const char *s1)
{
  register char *s;
  register size_t l = (concrete_strlen(s1) + 1) * (sizeof(char));
  if ((s = malloc(l)) != 0)
  {
    concrete_memcpy(s, s1, l);
  }
  return s;
}

static symbolic strdup_rec_len(const char *s, size_t n)
{
  symbolic c = (symbolic) ((unsigned long) (*((const unsigned char *) s)));
  cnstr_t end = _EQ_(c, 0);
  if (is_certain(end))
  {
    return (symbolic) n;
  }
  push_pc();
  assume(_NOT_(end));
  symbolic r = strdup_rec_len(s + 1, n + 1);
  pop_pc();
  return _ITE_VAR_(end, (symbolic) n, r);
}

static void strdup_rec_copy(char *dest, const char *src, size_t n, cnstr_t guard)
{
  symbolic c = (symbolic) ((unsigned long) (*((const unsigned char *) src)));
  cnstr_t end = _EQ_(c, 0);
  if (is_certain(end))
  {
    cond_write(dest, 0, guard);
    return;
  }
  push_pc();
  assume(_NOT_(end));
  cnstr_t g = _AND_(guard, _NOT_(end));
  cond_write(dest, c, g);
  strdup_rec_copy(dest + 1, src + 1, n + 1, g);
  pop_pc();
}

char *strdup(const char *s1)
{
  symbolic len = strdup_rec_len(s1, 0);
  size_t size = ((size_t) len) + 1;
  char *s = (char *) mem_alloc(size);
  if (s != 0)
  {
    strdup_rec_copy(s, s1, 0, 1);
  }
  return s;
}

void test_1()
{
  char s1[ARRAY_SIZE_1];
  for (int s1_idx_1 = 0; s1_idx_1 < ARRAY_SIZE_1; s1_idx_1++)
  {
    s1[s1_idx_1] = sym_var_array("s1", s1_idx_1, sizeof(char) * 8);
  }

  s1[ARRAY_SIZE_1 - 1] = '\0';
  state_t initial_state = save_current_state();
  mem_addr("s1", s1, ARRAY_SIZE_1);
  char * ret1 = concrete_strdup(s1);
  cnstr_t cnstr1 = get_cnstr(&ret1, sizeof(char *) * 8);
  store_cnstr("cnctr_test1", cnstr1);
  halt_all(initial_state);
  char * ret2 = strdup(s1);
  cnstr_t cnstr2 = get_cnstr(&ret2, sizeof(char *) * 8);
  store_cnstr("summ_test1", cnstr2);
  halt_all(NULL);
  result_t result = check_implications("cnctr_test1", "summ_test1");
  print_counterexamples(result);
  return ;
}

int main()
{
  test_1();
}