/* File generated by summboundverify */

#define NULL ((void*)0)
#define INT_SIZE (sizeof(int) * 8)
#define LONG_SIZE (sizeof(long) * 8)
#define CHAR_SIZE (sizeof(char) * 8)
#define PTR_SIZE (sizeof(void*) * 8)
typedef void* symbolic;
typedef int state_t;
typedef unsigned int size_t;
typedef unsigned int cnstr_t;
typedef unsigned int result_t;
typedef unsigned int list_t;

cnstr_t _ULE_(symbolic var1, symbolic var2) {return 0;}
cnstr_t get_cnstr(symbolic var, size_t size) {return 0;}
int is_sat(cnstr_t cnstr) {return 0;}
result_t check_implications(char* constraint1, char* constraint2) {return 0;}
state_t save_current_state() {return 0;}
symbolic sym_var_array(char* name, size_t index, size_t size) {return 0;}
symbolic sym_var_named(char* name, size_t size) {return 0;}
void assume(cnstr_t cnstr) {return;}
void halt_all(state_t state) {return;}
void mem_addr(char* name, void* addr, size_t length) {return;}
void print_counterexamples(result_t result) {return;}
void store_cnstr(char* name, cnstr_t constraint) {return;}

cnstr_t _AND_(cnstr_t cnstr1, cnstr_t cnstr2) {return 0;}
cnstr_t _EQ_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _NOT_(cnstr_t cnstr) {return 0;}
void cond_write(void* ptr, symbolic c, cnstr_t pc) {return;}
int is_certain(cnstr_t cnstr){return 0;}
void pop_pc(){return;}
void push_pc(){return;}

#define POINTER_SIZE 5
#define FUEL 5
#define ARRAY_SIZE_1 5
#define MAX_NUM_1 5

char *concrete_strcpy(char *s1, const char *s2)
{
  register char *s = s1;
  while ((*(s++) = *(s2++)) != 0)
    ;

  return s1;
}

static void strcpy_rec(char *d, const char *s, cnstr_t guard)
{
  symbolic c = (symbolic) ((unsigned long) (*((const unsigned char *) s)));
  cnstr_t end = _EQ_(c, 0);
  if (is_certain(end))
  {
    cond_write(d, 0, guard);
    return;
  }
  push_pc();
  assume(_NOT_(end));
  cnstr_t g = _AND_(guard, _NOT_(end));
  cond_write(d, c, g);
  strcpy_rec(d + 1, s + 1, g);
  pop_pc();
  cond_write(d, 0, _AND_(guard, end));
}

char *strcpy(char *dest, const char *src)
{
  strcpy_rec(dest, src, 1);
  return dest;
}

void test_1()
{
  char dest[ARRAY_SIZE_1];
  for (int dest_idx_1 = 0; dest_idx_1 < ARRAY_SIZE_1; dest_idx_1++)
  {
    dest[dest_idx_1] = sym_var_array("dest", dest_idx_1, sizeof(char) * 8);
  }

  dest[ARRAY_SIZE_1 - 1] = '\0';
  char src[ARRAY_SIZE_1];
  for (int src_idx_1 = 0; src_idx_1 < ARRAY_SIZE_1; src_idx_1++)
  {
    src[src_idx_1] = sym_var_array("src", src_idx_1, sizeof(char) * 8);
  }

  src[ARRAY_SIZE_1 - 1] = '\0';
  state_t initial_state = save_current_state();
  mem_addr("dest", dest, ARRAY_SIZE_1);
  mem_addr("src", src, ARRAY_SIZE_1);
  char * ret1 = concrete_strcpy(dest, src);
  cnstr_t cnstr1 = get_cnstr(&ret1, sizeof(char *) * 8);
  store_cnstr("cnctr_test1", cnstr1);
  halt_all(initial_state);
  char * ret2 = strcpy(dest, src);
  cnstr_t cnstr2 = get_cnstr(&ret2, sizeof(char *) * 8);
  store_cnstr("summ_test1", cnstr2);
  halt_all(NULL);
  result_t result = check_implications("cnctr_test1", "summ_test1");
  print_counterexamples(result);
  return ;
}

int main()
{
  test_1();
}