/* File generated by summboundverify */

#define NULL ((void*)0)
#define INT_SIZE (sizeof(int) * 8)
#define LONG_SIZE (sizeof(long) * 8)
#define CHAR_SIZE (sizeof(char) * 8)
#define PTR_SIZE (sizeof(void*) * 8)
typedef void* symbolic;
typedef int state_t;
typedef unsigned int size_t;
typedef unsigned int cnstr_t;
typedef unsigned int result_t;
typedef unsigned int list_t;

cnstr_t _ULE_(symbolic var1, symbolic var2) {return 0;}
cnstr_t get_cnstr(symbolic var, size_t size) {return 0;}
int is_sat(cnstr_t cnstr) {return 0;}
result_t check_implications(char* constraint1, char* constraint2) {return 0;}
state_t save_current_state() {return 0;}
symbolic sym_var_array(char* name, size_t index, size_t size) {return 0;}
symbolic sym_var_named(char* name, size_t size) {return 0;}
void assume(cnstr_t cnstr) {return;}
void halt_all(state_t state) {return;}
void mem_addr(char* name, void* addr, size_t length) {return;}
void print_counterexamples(result_t result) {return;}
void store_cnstr(char* name, cnstr_t constraint) {return;}

cnstr_t _EQ_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _ITE_VAR_(cnstr_t cnstr1, symbolic var1, symbolic var2) {return 0;}
cnstr_t _NOT_(cnstr_t cnstr) {return 0;}
cnstr_t _ULT_(symbolic var1, symbolic var2) {return 0;}
void allocd(void* ptr, size_t size) {return;}
int is_certain(cnstr_t cnstr){return 0;}
void pop_pc(){return;}
void push_pc(){return;}

#define POINTER_SIZE 5
#define FUEL 5
#define ARRAY_SIZE_1 5
#define MAX_NUM_1 5

int concrete_memcmp(const void *s1, const void *s2, size_t n)
{
  register const unsigned char *r1 = (const unsigned char *) s1;
  register const unsigned char *r2 = (const unsigned char *) s2;
  int r = 0;
  while ((n--) && ((r = ((int) (*(r1++))) - (*(r2++))) == 0))
    ;

  return r;
}

static symbolic memcmp_rec(const unsigned char *s1, const unsigned char *s2, size_t n)
{
  cnstr_t is_zero = _EQ_(n, (symbolic) 0);
  if (is_certain(is_zero))
  {
    return (symbolic) 0;
  }
  else
    if (is_certain(_NOT_(is_zero)))
  {
    symbolic v1 = (symbolic) (*s1);
    symbolic v2 = (symbolic) (*s2);
    cnstr_t eq = _EQ_(v1, v2);
    if (is_certain(eq))
    {
      return memcmp_rec(s1 + 1, s2 + 1, n - 1);
    }
    else
      if (is_certain(_NOT_(eq)))
    {
      cnstr_t lt = _ULT_(v1, v2);
      if (is_certain(lt))
      {
        return (symbolic) (((int) v1) - ((int) v2));
      }
      else
        if (is_certain(_NOT_(lt)))
      {
        return (symbolic) (((int) v1) - ((int) v2));
      }
      else
      {
        push_pc();
        assume(lt);
        symbolic r_lt = (symbolic) (((int) v1) - ((int) v2));
        pop_pc();
        push_pc();
        assume(_NOT_(lt));
        symbolic r_gt = (symbolic) (((int) v1) - ((int) v2));
        pop_pc();
        return _ITE_VAR_(lt, r_lt, r_gt);
      }
    }
    else
    {
      push_pc();
      assume(eq);
      symbolic r_eq = memcmp_rec(s1 + 1, s2 + 1, n - 1);
      pop_pc();
      push_pc();
      assume(_NOT_(eq));
      symbolic r_neq = (symbolic) (((int) v1) - ((int) v2));
      pop_pc();
      return _ITE_VAR_(eq, r_eq, r_neq);
    }
  }
  else
  {
    push_pc();
    assume(is_zero);
    symbolic r_zero = (symbolic) 0;
    pop_pc();
    push_pc();
    assume(_NOT_(is_zero));
    symbolic r_nonzero = memcmp_rec(s1, s2, n);
    pop_pc();
    return _ITE_VAR_(is_zero, r_zero, r_nonzero);
  }
}

int memcmp(const void *s1, const void *s2, size_t n)
{
  allocd(s1, n);
  allocd(s2, n);
  return (int) memcmp_rec((const unsigned char *) s1, (const unsigned char *) s2, n);
}

void test_1()
{
  char s1[ARRAY_SIZE_1];
  for (int s1_idx_1 = 0; s1_idx_1 < ARRAY_SIZE_1; s1_idx_1++)
  {
    s1[s1_idx_1] = sym_var_array("s1", s1_idx_1, sizeof(char) * 8);
  }

  s1[ARRAY_SIZE_1 - 1] = '\0';
  char s2[ARRAY_SIZE_1];
  for (int s2_idx_1 = 0; s2_idx_1 < ARRAY_SIZE_1; s2_idx_1++)
  {
    s2[s2_idx_1] = sym_var_array("s2", s2_idx_1, sizeof(char) * 8);
  }

  s2[ARRAY_SIZE_1 - 1] = '\0';
  size_t n = sym_var_named("n", sizeof(size_t) * 8);
  size_t max_1 = MAX_NUM_1;
  assume(_ULE_(n, max_1));
  state_t initial_state = save_current_state();
  int ret1 = concrete_memcmp(s1, s2, n);
  cnstr_t cnstr1 = get_cnstr(&ret1, sizeof(int) * 8);
  store_cnstr("cnctr_test1", cnstr1);
  halt_all(initial_state);
  int ret2 = memcmp(s1, s2, n);
  cnstr_t cnstr2 = get_cnstr(&ret2, sizeof(int) * 8);
  store_cnstr("summ_test1", cnstr2);
  halt_all(NULL);
  result_t result = check_implications("cnctr_test1", "summ_test1");
  print_counterexamples(result);
  return ;
}

int main()
{
  test_1();
}