/* File generated by summboundverify */

#define NULL ((void*)0)
#define INT_SIZE (sizeof(int) * 8)
#define LONG_SIZE (sizeof(long) * 8)
#define CHAR_SIZE (sizeof(char) * 8)
#define PTR_SIZE (sizeof(void*) * 8)
typedef void* symbolic;
typedef int state_t;
typedef unsigned int size_t;
typedef unsigned int cnstr_t;
typedef unsigned int result_t;
typedef unsigned int list_t;

cnstr_t _ULE_(symbolic var1, symbolic var2) {return 0;}
cnstr_t get_cnstr(symbolic var, size_t size) {return 0;}
int is_sat(cnstr_t cnstr) {return 0;}
result_t check_implications(char* constraint1, char* constraint2) {return 0;}
state_t save_current_state() {return 0;}
symbolic sym_var_array(char* name, size_t index, size_t size) {return 0;}
symbolic sym_var_named(char* name, size_t size) {return 0;}
void assume(cnstr_t cnstr) {return;}
void halt_all(state_t state) {return;}
void mem_addr(char* name, void* addr, size_t length) {return;}
void print_counterexamples(result_t result) {return;}
void store_cnstr(char* name, cnstr_t constraint) {return;}

cnstr_t _AND_(cnstr_t cnstr1, cnstr_t cnstr2) {return 0;}
cnstr_t _EQ_(symbolic var1, symbolic var2) {return 0;}
cnstr_t _ITE_VAR_(cnstr_t cnstr1, symbolic var1, symbolic var2) {return 0;}
cnstr_t _NOT_(cnstr_t cnstr) {return 0;}
void cond_write(void* ptr, symbolic c, cnstr_t pc) {return;}
int is_certain(cnstr_t cnstr){return 0;}
void pop_pc(){return;}
void push_pc(){return;}

#define POINTER_SIZE 5
#define FUEL 5
#define ARRAY_SIZE_1 5
#define MAX_NUM_1 5

char *concrete_stpncpy(register char *s1, register const char *s2, size_t n)
{
  char *s = s1;
  const char *p = s2;
  while (n)
  {
    if ((*s = *s2) != 0)
      s2++;
    ++s;
    --n;
  }

  return s1 + (s2 - p);
}

static symbolic stpncpy_rec(char *s1, const char *s2, size_t n, cnstr_t guard)
{
  cnstr_t end = _EQ_(n, 0);
  if (is_certain(end))
  {
    return 0;
  }
  push_pc();
  assume(_NOT_(end));
  cnstr_t g = _AND_(guard, _NOT_(end));
  symbolic c = (symbolic) ((unsigned char) (*s2));
  cnstr_t is_null = _EQ_(c, 0);
  symbolic steps_s2;
  if (is_certain(is_null))
  {
    cond_write(s1, c, g);
    steps_s2 = (symbolic) 0;
    push_pc();
    assume(_NOT_(end));
    cnstr_t g_inner = _AND_(g, is_null);
    pop_pc();
  }
  else
    if (is_certain(_NOT_(is_null)))
  {
    cond_write(s1, c, g);
    steps_s2 = 1 + ((size_t) stpncpy_rec(s1 + 1, s2 + 1, n - 1, g));
  }
  else
  {
    push_pc();
    assume(is_null);
    cond_write(s1, c, _AND_(g, is_null));
    symbolic a = 0 + ((size_t) stpncpy_rec(s1 + 1, s2, n - 1, _AND_(g, is_null)));
    pop_pc();
    push_pc();
    assume(_NOT_(is_null));
    cond_write(s1, c, _AND_(g, _NOT_(is_null)));
    symbolic b = 1 + ((size_t) stpncpy_rec(s1 + 1, s2 + 1, n - 1, _AND_(g, _NOT_(is_null))));
    pop_pc();
    steps_s2 = _ITE_VAR_(is_null, a, b);
  }
  if (is_certain(is_null))
  {
    steps_s2 = 0 + ((size_t) stpncpy_rec(s1 + 1, s2, n - 1, g));
  }
  pop_pc();
  return _ITE_VAR_(end, 0, steps_s2);
}

static symbolic stpncpy_step(char *s1, const char *s2, size_t n, cnstr_t guard)
{
  cnstr_t end = _EQ_(n, 0);
  if (is_certain(end))
    return 0;
  push_pc();
  assume(_NOT_(end));
  cnstr_t g = _AND_(guard, _NOT_(end));
  symbolic c = (symbolic) ((unsigned char) (*s2));
  cnstr_t is_null = _EQ_(c, 0);
  cond_write(s1, c, g);
  symbolic res;
  if (is_certain(is_null))
  {
    res = 0 + ((size_t) stpncpy_step(s1 + 1, s2, n - 1, g));
  }
  else
    if (is_certain(_NOT_(is_null)))
  {
    res = 1 + ((size_t) stpncpy_step(s1 + 1, s2 + 1, n - 1, g));
  }
  else
  {
    push_pc();
    assume(is_null);
    symbolic a = 0 + ((size_t) stpncpy_step(s1 + 1, s2, n - 1, _AND_(g, is_null)));
    pop_pc();
    push_pc();
    assume(_NOT_(is_null));
    symbolic b = 1 + ((size_t) stpncpy_step(s1 + 1, s2 + 1, n - 1, _AND_(g, _NOT_(is_null))));
    pop_pc();
    res = _ITE_VAR_(is_null, a, b);
  }
  pop_pc();
  return _ITE_VAR_(end, 0, res);
}

char *stpncpy(char *s1, const char *s2, size_t n)
{
  symbolic k = stpncpy_step(s1, s2, n, 1);
  return (char *) (((unsigned long) s1) + ((unsigned long) k));
}

void test_1()
{
  char s1[ARRAY_SIZE_1];
  for (int s1_idx_1 = 0; s1_idx_1 < ARRAY_SIZE_1; s1_idx_1++)
  {
    s1[s1_idx_1] = sym_var_array("s1", s1_idx_1, sizeof(char) * 8);
  }

  s1[ARRAY_SIZE_1 - 1] = '\0';
  char s2[ARRAY_SIZE_1];
  for (int s2_idx_1 = 0; s2_idx_1 < ARRAY_SIZE_1; s2_idx_1++)
  {
    s2[s2_idx_1] = sym_var_array("s2", s2_idx_1, sizeof(char) * 8);
  }

  s2[ARRAY_SIZE_1 - 1] = '\0';
  size_t n = sym_var_named("n", sizeof(size_t) * 8);
  size_t max_1 = MAX_NUM_1;
  assume(_ULE_(n, max_1));
  state_t initial_state = save_current_state();
  mem_addr("s1", s1, ARRAY_SIZE_1);
  mem_addr("s2", s2, ARRAY_SIZE_1);
  char * ret1 = concrete_stpncpy(s1, s2, n);
  cnstr_t cnstr1 = get_cnstr(&ret1, sizeof(char *) * 8);
  store_cnstr("cnctr_test1", cnstr1);
  halt_all(initial_state);
  char * ret2 = stpncpy(s1, s2, n);
  cnstr_t cnstr2 = get_cnstr(&ret2, sizeof(char *) * 8);
  store_cnstr("summ_test1", cnstr2);
  halt_all(NULL);
  result_t result = check_implications("cnctr_test1", "summ_test1");
  print_counterexamples(result);
  return ;
}

int main()
{
  test_1();
}